#! /bin/bash

# Parse output of terraform state to isolate and define variable $invoke_url for lambda emailer
# If you mess with the module structure of the terraform scripts, you'll need to run `terraform state list`
# to figure out the
eval $(terraform state show -no-color module.api_gateway_triggering_lambda_module.aws_api_gateway_deployment.production | grep invoke_url | sed 's/ //g')

# Exit if $invoke_url failed to set
if [[ -z $invoke_url ]]; then
  echo ">>> invoke_url has no value"
  exit
fi

# Print and export $invoke_url
[[ $1 != '--quiet' ]] && echo -e """${RED}
==============================================================================
The invoke url is ${WHI} ${invoke_url} ${RED}
==============================================================================
${WHI}"""
export invoke_url=$invoke_url
